config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"

  scope module: 'admin' do 
    get 'admin-home' => 'home#index', as: :admin_home
  end

  scope module: 'guest' do 
    get 'product' => 'product#index', as: :product
    get 'about' => 'about#index',as: :about
  end 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController

    def index 
    end 

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    # before_action :authenticate_user!

    layout 'admin'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guest/about_controller.rb
class Guest::AboutController < ApplicationController 

    def index
    end 

end

app/controllers/guest/product_controller.rb
class Guest::ProductController < ApplicationController 

    def index 
    end 

end

app/controllers/guest_controller.rb
class GuestController < ApplicationController

    layout 'guest'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 

    def index
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/home/index.html.erb
<p>This is admin home page</p>

app/views/guest/about/index.html.erb
<p>This is about page</p>

app/views/guest/product/index.html.erb
<p>This is product page</p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appphonestore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="row">
        <div class="col-lg-4 col-md-5 col-sm-12 bg-secondary">
            <%= link_to "Home", root_path, class: 'fs-3 fw-bold text-white' %>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi ipsum molestiae sapiente est ea ratione aliquam iusto necessitatibus dolores error.
        </div>
        <div class="col-lg-8 col-md-7 col-sm-12 bg-light">
            <%= yield %>
        </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appphonestore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/guest.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appphonestore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navigation" %>
    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Home", root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Product", product_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            admin@gmail.com
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Admin", admin_home_path, class: 'dropdown-item' %></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/welcome/index.html.erb
<div>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum expedita perferendis accusamus ut facere, maxime esse, quae voluptatibus aliquid veniam facilis? Unde sint rem ab numquam nisi officiis maiores similique.</p>
</div>